version: '3'

services:
  eureka:
    image: maven:3.6.1-jdk-8
    ports:
      - '8761:8761'
    working_dir: /app
    volumes:
      - ./eureka-server:/app
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - "./rabbitmq_data:/data"
  api-gateway:
    image: maven:3.6.1-jdk-8
    ports:
      - '8080:8080'
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    depends_on:
      - eureka
      - rabbitmq
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  userdbdev:
    image: postgres
    ports:
     - "5401:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=userdev
  profiledbdev:
    image: postgres
    ports:
     - "5404:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=profiledev
  postsdbdev:
    image: postgres
    ports:
     - "5402:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postsdev
  commentsdbdev:
    image: postgres
    ports:
     - "5403:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=commentsdev
  users-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '5001:5001'
    working_dir: /app
    volumes:
      - ./users-api:/app
    depends_on:
       - eureka
       - rabbitmq
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  profile-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '5004:5004'
    working_dir: /app
    volumes:
      - ./profile-api:/app
    depends_on:
       - eureka
       - rabbitmq
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  posts-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '5002:5002'
    working_dir: /app
    volumes:
      - ./posts-api:/app
    depends_on:
       - eureka
       - rabbitmq
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  comments-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '5003:5003'
    working_dir: /app
    volumes:
      - ./comments-api:/app
    depends_on:
       - eureka
       - rabbitmq
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev

    